version: '3.8'

services:
  postgres:
    container_name: postgres
    build: './db'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crickalysis
    ports:
      - "5432:5432"
  